/**
 * LEGADO NÃO CANÔNICO (Frente Y): transcrição sem documento-fonte verificável no projeto (sem hash, localizador
 * nem edição comprovada). Não é fonte oficial; novos consumidores devem usar src/features/curricular-reference/.
 */
/**
 * DADO curricular — BNCC (MEC/CNE, 2018), Educação Infantil, objetivos de
 * aprendizagem e desenvolvimento EI01/EI02/EI03 nos cinco Campos de Experiências.
 * Código e texto oficial transcritos da "Base Pedagógica Mestre BNCC SAEB SIGEM"
 * (status: OFICIAL — código/texto). Nenhum componente consome este arquivo
 * diretamente: a entrada é o repositório da Matriz de Habilidades.
 */
export const BNCC_INFANT_SOURCE = {
  sourceId: "bncc",
  label: "BNCC — Base Nacional Comum Curricular",
  authority: "MEC / CNE",
  version: "2018",
  url: "https://basenacionalcomum.mec.gov.br/images/BNCC_EI_EF_110518_versaofinal_site.pdf",
} as const;

export const BNCC_INFANT_ROWS: readonly { code: string; fieldId: string; officialText: string }[] = [
  { code: "EI01CG01", fieldId: "corpo-gestos", officialText: "Movimentar as partes do corpo para exprimir corporalmente emoções, necessidades e desejos." },
  { code: "EI01CG02", fieldId: "corpo-gestos", officialText: "Experimentar as possibilidades corporais nas brincadeiras e interações em ambientes acolhedores e desafiantes." },
  { code: "EI01CG03", fieldId: "corpo-gestos", officialText: "Imitar gestos e movimentos de outras crianças, adultos e animais." },
  { code: "EI01CG04", fieldId: "corpo-gestos", officialText: "Participar do cuidado do seu corpo e da promoção do seu bem-estar." },
  { code: "EI01CG05", fieldId: "corpo-gestos", officialText: "Utilizar os movimentos de preensão, encaixe e lançamento, ampliando suas possibilidades de manuseio de diferentes materiais e objetos." },
  { code: "EI01EF01", fieldId: "escuta-fala", officialText: "Reconhecer quando é chamado por seu nome e reconhecer os nomes de pessoas com quem convive." },
  { code: "EI01EF02", fieldId: "escuta-fala", officialText: "Demonstrar interesse ao ouvir a leitura de poemas e a apresentação de músicas." },
  { code: "EI01EF03", fieldId: "escuta-fala", officialText: "Demonstrar interesse ao ouvir histórias lidas ou contadas, observando ilustrações e os movimentos de leitura do adulto-leitor (modo de segurar o portador e de virar as páginas)." },
  { code: "EI01EF04", fieldId: "escuta-fala", officialText: "Reconhecer elementos das ilustrações de histórias, apontando-os, a pedido do adulto-leitor." },
  { code: "EI01EF05", fieldId: "escuta-fala", officialText: "Imitar as variações de entonação e gestos realizados pelos adultos, ao ler histórias e ao cantar." },
  { code: "EI01EF06", fieldId: "escuta-fala", officialText: "Comunicar-se com outras pessoas usando movimentos, gestos, balbucios, fala e outras formas de expressão." },
  { code: "EI01EF07", fieldId: "escuta-fala", officialText: "Conhecer e manipular materiais impressos e audiovisuais em diferentes portadores (livro, revista, gibi, jornal, cartaz, CD, tablet etc.)." },
  { code: "EI01EF08", fieldId: "escuta-fala", officialText: "Participar de situações de escuta de textos em diferentes gêneros textuais (poemas, fábulas, contos, receitas, quadrinhos, anúncios etc.)." },
  { code: "EI01EF09", fieldId: "escuta-fala", officialText: "Conhecer e manipular diferentes instrumentos e suportes de escrita." },
  { code: "EI01EO01", fieldId: "eu-outro-nos", officialText: "Perceber que suas ações têm efeitos nas outras crianças e nos adultos." },
  { code: "EI01EO02", fieldId: "eu-outro-nos", officialText: "Perceber as possibilidades e os limites de seu corpo nas brincadeiras e interações das quais participa." },
  { code: "EI01EO03", fieldId: "eu-outro-nos", officialText: "Interagir com crianças da mesma faixa etária e adultos ao explorar espaços, materiais, objetos, brinquedos." },
  { code: "EI01EO04", fieldId: "eu-outro-nos", officialText: "Comunicar necessidades, desejos e emoções, utilizando gestos, balbucios, palavras." },
  { code: "EI01EO05", fieldId: "eu-outro-nos", officialText: "Reconhecer seu corpo e expressar suas sensações em momentos de alimentação, higiene, brincadeira e descanso." },
  { code: "EI01EO06", fieldId: "eu-outro-nos", officialText: "Interagir com outras crianças da mesma faixa etária e adultos, adaptando-se ao convívio social." },
  { code: "EI01ET01", fieldId: "espacos-tempos", officialText: "Explorar e descobrir as propriedades de objetos e materiais (odor, cor, sabor, temperatura)." },
  { code: "EI01ET02", fieldId: "espacos-tempos", officialText: "Explorar relações de causa e efeito (transbordar, tingir, misturar, mover e remover etc.) na interação com o mundo físico." },
  { code: "EI01ET03", fieldId: "espacos-tempos", officialText: "Explorar o ambiente pela ação e observação, manipulando, experimentando e fazendo descobertas." },
  { code: "EI01ET04", fieldId: "espacos-tempos", officialText: "Manipular, experimentar, arrumar e explorar o espaço por meio de experiências de deslocamentos de si e dos objetos." },
  { code: "EI01ET05", fieldId: "espacos-tempos", officialText: "Manipular materiais diversos e variados para comparar as diferenças e semelhanças entre eles." },
  { code: "EI01ET06", fieldId: "espacos-tempos", officialText: "Vivenciar diferentes ritmos, velocidades e fluxos nas interações e brincadeiras (em danças, balanços, escorregadores etc.)." },
  { code: "EI01TS01", fieldId: "tracos-sons", officialText: "Explorar sons produzidos com o próprio corpo e com objetos do ambiente." },
  { code: "EI01TS02", fieldId: "tracos-sons", officialText: "Traçar marcas gráficas, em diferentes suportes, usando instrumentos riscantes e tintas." },
  { code: "EI01TS03", fieldId: "tracos-sons", officialText: "Explorar diferentes fontes sonoras e materiais para acompanhar brincadeiras cantadas, canções, músicas e melodias." },
  { code: "EI02CG01", fieldId: "corpo-gestos", officialText: "Apropriar-se de gestos e movimentos de sua cultura no cuidado de si e nos jogos e brincadeiras." },
  { code: "EI02CG02", fieldId: "corpo-gestos", officialText: "Deslocar seu corpo no espaço, orientando-se por noções como em frente, atrás, no alto, embaixo, dentro, fora etc., ao se envolver em brincadeiras e atividades de diferentes naturezas." },
  { code: "EI02CG03", fieldId: "corpo-gestos", officialText: "Explorar formas de deslocamento no espaço (pular, saltar, dançar), combinando movimentos e seguindo orientações." },
  { code: "EI02CG04", fieldId: "corpo-gestos", officialText: "Demonstrar progressiva independência no cuidado do seu corpo." },
  { code: "EI02CG05", fieldId: "corpo-gestos", officialText: "Desenvolver progressivamente as habilidades manuais, adquirindo controle para desenhar, pintar, rasgar, folhear, entre outros." },
  { code: "EI02EF01", fieldId: "escuta-fala", officialText: "Dialogar com crianças e adultos, expressando seus desejos, necessidades, sentimentos e opiniões." },
  { code: "EI02EF02", fieldId: "escuta-fala", officialText: "Identificar e criar diferentes sons e reconhecer rimas e aliterações em cantigas de roda e textos poéticos." },
  { code: "EI02EF03", fieldId: "escuta-fala", officialText: "Demonstrar interesse e atenção ao ouvir a leitura de histórias e outros textos, diferenciando escrita de ilustrações, e acompanhando, com orientação do adulto-leitor, a direção da leitura (de cima para baixo, da esquerda para a direita)." },
  { code: "EI02EF04", fieldId: "escuta-fala", officialText: "Formular e responder perguntas sobre fatos da história narrada, identificando cenários, personagens e principais acontecimentos." },
  { code: "EI02EF05", fieldId: "escuta-fala", officialText: "Relatar experiências e fatos acontecidos, histórias ouvidas, filmes ou peças teatrais assistidos etc." },
  { code: "EI02EF06", fieldId: "escuta-fala", officialText: "Criar e contar histórias oralmente, com base em imagens ou temas sugeridos." },
  { code: "EI02EF07", fieldId: "escuta-fala", officialText: "Manusear diferentes portadores textuais, demonstrando reconhecer seus usos sociais." },
  { code: "EI02EF08", fieldId: "escuta-fala", officialText: "Manipular textos e participar de situações de escuta para ampliar seu contato com diferentes gêneros textuais (parlendas, histórias de aventura, tirinhas, cartazes de sala, cardápios, notícias etc.)." },
  { code: "EI02EF09", fieldId: "escuta-fala", officialText: "Manusear diferentes instrumentos e suportes de escrita para desenhar, traçar letras e outros sinais gráficos." },
  { code: "EI02EO01", fieldId: "eu-outro-nos", officialText: "Demonstrar atitudes de cuidado e solidariedade na interação com crianças e adultos." },
  { code: "EI02EO02", fieldId: "eu-outro-nos", officialText: "Demonstrar imagem positiva de si e confiança em sua capacidade para enfrentar dificuldades e desafios." },
  { code: "EI02EO03", fieldId: "eu-outro-nos", officialText: "Compartilhar os objetos e os espaços com crianças da mesma faixa etária e adultos." },
  { code: "EI02EO04", fieldId: "eu-outro-nos", officialText: "Comunicar-se com os colegas e os adultos, buscando compreendê-los e fazendo-se compreender." },
  { code: "EI02EO05", fieldId: "eu-outro-nos", officialText: "Perceber que as pessoas têm características físicas diferentes, respeitando essas diferenças." },
  { code: "EI02EO06", fieldId: "eu-outro-nos", officialText: "Respeitar regras básicas de convívio social nas interações e brincadeiras." },
  { code: "EI02EO07", fieldId: "eu-outro-nos", officialText: "Resolver conflitos nas interações e brincadeiras, com a orientação de um adulto." },
  { code: "EI02ET01", fieldId: "espacos-tempos", officialText: "Explorar e descrever semelhanças e diferenças entre as características e propriedades dos objetos (textura, massa, tamanho)." },
  { code: "EI02ET02", fieldId: "espacos-tempos", officialText: "Observar, relatar e descrever incidentes do cotidiano e fenômenos naturais (luz solar, vento, chuva etc.)." },
  { code: "EI02ET03", fieldId: "espacos-tempos", officialText: "Compartilhar, com outras crianças, situações de cuidado de plantas e animais nos espaços da instituição e fora dela." },
  { code: "EI02ET04", fieldId: "espacos-tempos", officialText: "Identificar relações espaciais (dentro e fora, em cima, embaixo, acima, abaixo, entre e do lado) e temporais (antes, durante e depois)." },
  { code: "EI02ET05", fieldId: "espacos-tempos", officialText: "Classificar objetos, considerando determinado atributo (tamanho, peso, cor, forma etc.)." },
  { code: "EI02ET06", fieldId: "espacos-tempos", officialText: "Utilizar conceitos básicos de tempo (agora, antes, durante, depois, ontem, hoje, amanhã, lento, rápido, depressa, devagar)." },
  { code: "EI02ET07", fieldId: "espacos-tempos", officialText: "Contar oralmente objetos, pessoas, livros etc., em contextos diversos." },
  { code: "EI02ET08", fieldId: "espacos-tempos", officialText: "Registrar com números a quantidade de crianças (meninas e meninos, presentes e ausentes) e a quantidade de objetos da mesma natureza (bonecas, bolas, livros etc.)." },
  { code: "EI02TS01", fieldId: "tracos-sons", officialText: "Criar sons com materiais, objetos e instrumentos musicais, para acompanhar diversos ritmos de música." },
  { code: "EI02TS02", fieldId: "tracos-sons", officialText: "Utilizar materiais variados com possibilidades de manipulação (argila, massa de modelar), explorando cores, texturas, superfícies, planos, formas e volumes ao criar objetos tridimensionais." },
  { code: "EI02TS03", fieldId: "tracos-sons", officialText: "Utilizar diferentes fontes sonoras disponíveis no ambiente em brincadeiras cantadas, canções, músicas e melodias." },
  { code: "EI03CG01", fieldId: "corpo-gestos", officialText: "Criar com o corpo formas diversificadas de expressão de sentimentos, sensações e emoções, tanto nas situações do cotidiano quanto em brincadeiras, dança, teatro, música." },
  { code: "EI03CG02", fieldId: "corpo-gestos", officialText: "Demonstrar controle e adequação do uso de seu corpo em brincadeiras e jogos, escuta e reconto de histórias, atividades artísticas, entre outras possibilidades." },
  { code: "EI03CG03", fieldId: "corpo-gestos", officialText: "Criar movimentos, gestos, olhares e mímicas em brincadeiras, jogos e atividades artísticas como dança, teatro e música." },
  { code: "EI03CG04", fieldId: "corpo-gestos", officialText: "Adotar hábitos de autocuidado relacionados a higiene, alimentação, conforto e aparência." },
  { code: "EI03CG05", fieldId: "corpo-gestos", officialText: "Coordenar suas habilidades manuais no atendimento adequado a seus interesses e necessidades em situações diversas." },
  { code: "EI03EF01", fieldId: "escuta-fala", officialText: "Expressar ideias, desejos e sentimentos sobre suas vivências, por meio da linguagem oral e escrita (escrita espontânea), de fotos, desenhos e outras formas de expressão." },
  { code: "EI03EF02", fieldId: "escuta-fala", officialText: "Inventar brincadeiras cantadas, poemas e canções, criando rimas, aliterações e ritmos." },
  { code: "EI03EF03", fieldId: "escuta-fala", officialText: "Escolher e folhear livros, procurando orientar-se por temas e ilustrações e tentando identificar palavras conhecidas." },
  { code: "EI03EF04", fieldId: "escuta-fala", officialText: "Recontar histórias ouvidas e planejar coletivamente roteiros de vídeos e de encenações, definindo os contextos, os personagens, a estrutura da história." },
  { code: "EI03EF05", fieldId: "escuta-fala", officialText: "Recontar histórias ouvidas para produção de reconto escrito, tendo o professor como escriba." },
  { code: "EI03EF06", fieldId: "escuta-fala", officialText: "Produzir suas próprias histórias orais e escritas (escrita espontânea), em situações com função social significativa." },
  { code: "EI03EF07", fieldId: "escuta-fala", officialText: "Levantar hipóteses sobre gêneros textuais veiculados em portadores conhecidos, recorrendo a estratégias de observação gráfica e/ou de leitura." },
  { code: "EI03EF08", fieldId: "escuta-fala", officialText: "Selecionar livros e textos de gêneros conhecidos para a leitura de um adulto e/ou para sua própria leitura (partindo de seu repertório sobre esses textos, como a recuperação pela memória, pela leitura das ilustrações etc.)." },
  { code: "EI03EF09", fieldId: "escuta-fala", officialText: "Levantar hipóteses em relação à linguagem escrita, realizando registros de palavras e textos, por meio de escrita espontânea." },
  { code: "EI03EO01", fieldId: "eu-outro-nos", officialText: "Demonstrar empatia pelos outros, percebendo que as pessoas têm diferentes sentimentos, necessidades e maneiras de pensar e agir." },
  { code: "EI03EO02", fieldId: "eu-outro-nos", officialText: "Agir de maneira independente, com confiança em suas capacidades, reconhecendo suas conquistas e limitações." },
  { code: "EI03EO03", fieldId: "eu-outro-nos", officialText: "Ampliar as relações interpessoais, desenvolvendo atitudes de participação e cooperação." },
  { code: "EI03EO04", fieldId: "eu-outro-nos", officialText: "Comunicar suas ideias e sentimentos a pessoas e grupos diversos." },
  { code: "EI03EO05", fieldId: "eu-outro-nos", officialText: "Demonstrar valorização das características de seu corpo e respeitar as características dos outros (crianças e adultos) com os quais convive." },
  { code: "EI03EO06", fieldId: "eu-outro-nos", officialText: "Manifestar interesse e respeito por diferentes culturas e modos de vida." },
  { code: "EI03EO07", fieldId: "eu-outro-nos", officialText: "Usar estratégias pautadas no respeito mútuo para lidar com conflitos nas interações com crianças e adultos." },
  { code: "EI03ET01", fieldId: "espacos-tempos", officialText: "Estabelecer relações de comparação entre objetos, observando suas propriedades." },
  { code: "EI03ET02", fieldId: "espacos-tempos", officialText: "Observar e descrever mudanças em diferentes materiais, resultantes de ações sobre eles, em experimentos envolvendo fenômenos naturais e artificiais." },
  { code: "EI03ET03", fieldId: "espacos-tempos", officialText: "Identificar e selecionar fontes de informações, para responder a questões sobre a natureza, seus fenômenos, sua conservação." },
  { code: "EI03ET04", fieldId: "espacos-tempos", officialText: "Registrar observações, manipulações e medidas, usando múltiplas linguagens (desenho, registro por números ou escrita espontânea), em diferentes suportes." },
  { code: "EI03ET05", fieldId: "espacos-tempos", officialText: "Classificar objetos e figuras de acordo com suas semelhanças e diferenças." },
  { code: "EI03ET06", fieldId: "espacos-tempos", officialText: "Relatar fatos importantes sobre seu nascimento e desenvolvimento, a história dos seus familiares e da sua comunidade." },
  { code: "EI03ET07", fieldId: "espacos-tempos", officialText: "Relacionar números às suas respectivas quantidades e identificar o antes, o depois e o entre em uma sequência." },
  { code: "EI03ET08", fieldId: "espacos-tempos", officialText: "Expressar medidas (peso, altura etc.), construindo gráficos básicos." },
  { code: "EI03TS01", fieldId: "tracos-sons", officialText: "Utilizar sons produzidos por materiais, objetos e instrumentos musicais durante brincadeiras de faz de conta, encenações, criações musicais, festas." },
  { code: "EI03TS02", fieldId: "tracos-sons", officialText: "Expressar-se livremente por meio de desenho, pintura, colagem, dobradura e escultura, criando produções bidimensionais e tridimensionais." },
  { code: "EI03TS03", fieldId: "tracos-sons", officialText: "Reconhecer as qualidades do som (intensidade, duração, altura e timbre), utilizando-as em suas produções sonoras e ao ouvir músicas e sons." },
];
