import { renderToStaticMarkup } from "react-dom/server";
import { richFixture } from "@/features/calendar/calendar-external-rich-fixture";
import { buildPrintModel } from "@/features/calendar/institutional-calendar-presentation";
import { externalPresentation } from "@/features/calendar/calendar-visual-resolver";
import { buildExternalViewModel, defaultProfile } from "@/features/calendar/calendar-external-model";
import { FreeSheet } from "@/features/calendar/calendar-external-sheets";
import { applyPremium } from "@/features/calendar/calendar-external-premium";
const f = richFixture(); const pres = externalPresentation(f.presentation);
const vm = buildExternalViewModel(buildPrintModel(pres, f.days, f.periods), pres, { versionId: "v", config: f.council, days: f.days });
const p = applyPremium(defaultProfile("externo-livre", pres));
console.log(renderToStaticMarkup(<FreeSheet vm={vm} p={p} presentation={pres} template={"externo-livre" as never} />));
