/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlunosRouteImport } from './routes/alunos'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MatriculasRouteImport } from './routes/matriculas'
import { Route as MatrizesCurricularesRouteImport } from './routes/matrizes-curriculares'
import { Route as TurmasRouteImport } from './routes/turmas'
import { Route as UnidadesRouteImport } from './routes/unidades'
import { Route as AlunosIndexRouteImport } from './routes/alunos.index'
import { Route as AlunosIdRouteImport } from './routes/alunos.$id'
import { Route as AlunosNovoRouteImport } from './routes/alunos.novo'
import { Route as MatrizesCurricularesIndexRouteImport } from './routes/matrizes-curriculares.index'
import { Route as MatrizesCurricularesIdRouteImport } from './routes/matrizes-curriculares.$id'
import { Route as MatrizesCurricularesNovaRouteImport } from './routes/matrizes-curriculares.nova'
import { Route as TurmasIndexRouteImport } from './routes/turmas.index'
import { Route as TurmasIdRouteImport } from './routes/turmas.$id'
import { Route as TurmasNovaRouteImport } from './routes/turmas.nova'
import { Route as UnidadesIndexRouteImport } from './routes/unidades.index'
import { Route as UnidadesIdRouteImport } from './routes/unidades.$id'
import { Route as AlunosEditarIdRouteImport } from './routes/alunos.editar.$id'
import { Route as MatrizesCurricularesImpressaoIdRouteImport } from './routes/matrizes-curriculares.impressao.$id'
import { Route as MatrizesCurricularesNovaVersaoIdRouteImport } from './routes/matrizes-curriculares.nova-versao.$id'
import { Route as MatrizesCurricularesRascunhoIdRouteImport } from './routes/matrizes-curriculares.rascunho.$id'
import { Route as TurmasEditarIdRouteImport } from './routes/turmas.editar.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunosRoute = AlunosRouteImport.update({
  id: '/alunos',
  path: '/alunos',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MatriculasRoute = MatriculasRouteImport.update({
  id: '/matriculas',
  path: '/matriculas',
  getParentRoute: () => rootRouteImport,
} as any)
const MatrizesCurricularesRoute = MatrizesCurricularesRouteImport.update({
  id: '/matrizes-curriculares',
  path: '/matrizes-curriculares',
  getParentRoute: () => rootRouteImport,
} as any)
const TurmasRoute = TurmasRouteImport.update({
  id: '/turmas',
  path: '/turmas',
  getParentRoute: () => rootRouteImport,
} as any)
const UnidadesRoute = UnidadesRouteImport.update({
  id: '/unidades',
  path: '/unidades',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunosIndexRoute = AlunosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AlunosRoute,
} as any)
const AlunosIdRoute = AlunosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AlunosRoute,
} as any)
const AlunosNovoRoute = AlunosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AlunosRoute,
} as any)
const MatrizesCurricularesIndexRoute =
  MatrizesCurricularesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => MatrizesCurricularesRoute,
  } as any)
const MatrizesCurricularesIdRoute = MatrizesCurricularesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MatrizesCurricularesRoute,
} as any)
const MatrizesCurricularesNovaRoute =
  MatrizesCurricularesNovaRouteImport.update({
    id: '/nova',
    path: '/nova',
    getParentRoute: () => MatrizesCurricularesRoute,
  } as any)
const TurmasIndexRoute = TurmasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TurmasRoute,
} as any)
const TurmasIdRoute = TurmasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TurmasRoute,
} as any)
const TurmasNovaRoute = TurmasNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => TurmasRoute,
} as any)
const UnidadesIndexRoute = UnidadesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UnidadesRoute,
} as any)
const UnidadesIdRoute = UnidadesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => UnidadesRoute,
} as any)
const AlunosEditarIdRoute = AlunosEditarIdRouteImport.update({
  id: '/editar/$id',
  path: '/editar/$id',
  getParentRoute: () => AlunosRoute,
} as any)
const MatrizesCurricularesImpressaoIdRoute =
  MatrizesCurricularesImpressaoIdRouteImport.update({
    id: '/impressao/$id',
    path: '/impressao/$id',
    getParentRoute: () => MatrizesCurricularesRoute,
  } as any)
const MatrizesCurricularesNovaVersaoIdRoute =
  MatrizesCurricularesNovaVersaoIdRouteImport.update({
    id: '/nova-versao/$id',
    path: '/nova-versao/$id',
    getParentRoute: () => MatrizesCurricularesRoute,
  } as any)
const MatrizesCurricularesRascunhoIdRoute =
  MatrizesCurricularesRascunhoIdRouteImport.update({
    id: '/rascunho/$id',
    path: '/rascunho/$id',
    getParentRoute: () => MatrizesCurricularesRoute,
  } as any)
const TurmasEditarIdRoute = TurmasEditarIdRouteImport.update({
  id: '/editar/$id',
  path: '/editar/$id',
  getParentRoute: () => TurmasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alunos': typeof AlunosRouteWithChildren
  '/design-system': typeof DesignSystemRoute
  '/login': typeof LoginRoute
  '/matriculas': typeof MatriculasRoute
  '/matrizes-curriculares': typeof MatrizesCurricularesRouteWithChildren
  '/turmas': typeof TurmasRouteWithChildren
  '/unidades': typeof UnidadesRouteWithChildren
  '/alunos/$id': typeof AlunosIdRoute
  '/alunos/novo': typeof AlunosNovoRoute
  '/matrizes-curriculares/$id': typeof MatrizesCurricularesIdRoute
  '/matrizes-curriculares/nova': typeof MatrizesCurricularesNovaRoute
  '/turmas/$id': typeof TurmasIdRoute
  '/turmas/nova': typeof TurmasNovaRoute
  '/unidades/$id': typeof UnidadesIdRoute
  '/alunos/': typeof AlunosIndexRoute
  '/matrizes-curriculares/': typeof MatrizesCurricularesIndexRoute
  '/turmas/': typeof TurmasIndexRoute
  '/unidades/': typeof UnidadesIndexRoute
  '/alunos/editar/$id': typeof AlunosEditarIdRoute
  '/matrizes-curriculares/impressao/$id': typeof MatrizesCurricularesImpressaoIdRoute
  '/matrizes-curriculares/nova-versao/$id': typeof MatrizesCurricularesNovaVersaoIdRoute
  '/matrizes-curriculares/rascunho/$id': typeof MatrizesCurricularesRascunhoIdRoute
  '/turmas/editar/$id': typeof TurmasEditarIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design-system': typeof DesignSystemRoute
  '/login': typeof LoginRoute
  '/matriculas': typeof MatriculasRoute
  '/alunos/$id': typeof AlunosIdRoute
  '/alunos/novo': typeof AlunosNovoRoute
  '/matrizes-curriculares/$id': typeof MatrizesCurricularesIdRoute
  '/matrizes-curriculares/nova': typeof MatrizesCurricularesNovaRoute
  '/turmas/$id': typeof TurmasIdRoute
  '/turmas/nova': typeof TurmasNovaRoute
  '/unidades/$id': typeof UnidadesIdRoute
  '/alunos': typeof AlunosIndexRoute
  '/matrizes-curriculares': typeof MatrizesCurricularesIndexRoute
  '/turmas': typeof TurmasIndexRoute
  '/unidades': typeof UnidadesIndexRoute
  '/alunos/editar/$id': typeof AlunosEditarIdRoute
  '/matrizes-curriculares/impressao/$id': typeof MatrizesCurricularesImpressaoIdRoute
  '/matrizes-curriculares/nova-versao/$id': typeof MatrizesCurricularesNovaVersaoIdRoute
  '/matrizes-curriculares/rascunho/$id': typeof MatrizesCurricularesRascunhoIdRoute
  '/turmas/editar/$id': typeof TurmasEditarIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alunos': typeof AlunosRouteWithChildren
  '/design-system': typeof DesignSystemRoute
  '/login': typeof LoginRoute
  '/matriculas': typeof MatriculasRoute
  '/matrizes-curriculares': typeof MatrizesCurricularesRouteWithChildren
  '/turmas': typeof TurmasRouteWithChildren
  '/unidades': typeof UnidadesRouteWithChildren
  '/alunos/$id': typeof AlunosIdRoute
  '/alunos/novo': typeof AlunosNovoRoute
  '/matrizes-curriculares/$id': typeof MatrizesCurricularesIdRoute
  '/matrizes-curriculares/nova': typeof MatrizesCurricularesNovaRoute
  '/turmas/$id': typeof TurmasIdRoute
  '/turmas/nova': typeof TurmasNovaRoute
  '/unidades/$id': typeof UnidadesIdRoute
  '/alunos/': typeof AlunosIndexRoute
  '/matrizes-curriculares/': typeof MatrizesCurricularesIndexRoute
  '/turmas/': typeof TurmasIndexRoute
  '/unidades/': typeof UnidadesIndexRoute
  '/alunos/editar/$id': typeof AlunosEditarIdRoute
  '/matrizes-curriculares/impressao/$id': typeof MatrizesCurricularesImpressaoIdRoute
  '/matrizes-curriculares/nova-versao/$id': typeof MatrizesCurricularesNovaVersaoIdRoute
  '/matrizes-curriculares/rascunho/$id': typeof MatrizesCurricularesRascunhoIdRoute
  '/turmas/editar/$id': typeof TurmasEditarIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alunos'
    | '/design-system'
    | '/login'
    | '/matriculas'
    | '/matrizes-curriculares'
    | '/turmas'
    | '/unidades'
    | '/alunos/$id'
    | '/alunos/novo'
    | '/matrizes-curriculares/$id'
    | '/matrizes-curriculares/nova'
    | '/turmas/$id'
    | '/turmas/nova'
    | '/unidades/$id'
    | '/alunos/'
    | '/matrizes-curriculares/'
    | '/turmas/'
    | '/unidades/'
    | '/alunos/editar/$id'
    | '/matrizes-curriculares/impressao/$id'
    | '/matrizes-curriculares/nova-versao/$id'
    | '/matrizes-curriculares/rascunho/$id'
    | '/turmas/editar/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/design-system'
    | '/login'
    | '/matriculas'
    | '/alunos/$id'
    | '/alunos/novo'
    | '/matrizes-curriculares/$id'
    | '/matrizes-curriculares/nova'
    | '/turmas/$id'
    | '/turmas/nova'
    | '/unidades/$id'
    | '/alunos'
    | '/matrizes-curriculares'
    | '/turmas'
    | '/unidades'
    | '/alunos/editar/$id'
    | '/matrizes-curriculares/impressao/$id'
    | '/matrizes-curriculares/nova-versao/$id'
    | '/matrizes-curriculares/rascunho/$id'
    | '/turmas/editar/$id'
  id:
    | '__root__'
    | '/'
    | '/alunos'
    | '/design-system'
    | '/login'
    | '/matriculas'
    | '/matrizes-curriculares'
    | '/turmas'
    | '/unidades'
    | '/alunos/$id'
    | '/alunos/novo'
    | '/matrizes-curriculares/$id'
    | '/matrizes-curriculares/nova'
    | '/turmas/$id'
    | '/turmas/nova'
    | '/unidades/$id'
    | '/alunos/'
    | '/matrizes-curriculares/'
    | '/turmas/'
    | '/unidades/'
    | '/alunos/editar/$id'
    | '/matrizes-curriculares/impressao/$id'
    | '/matrizes-curriculares/nova-versao/$id'
    | '/matrizes-curriculares/rascunho/$id'
    | '/turmas/editar/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlunosRoute: typeof AlunosRouteWithChildren
  DesignSystemRoute: typeof DesignSystemRoute
  LoginRoute: typeof LoginRoute
  MatriculasRoute: typeof MatriculasRoute
  MatrizesCurricularesRoute: typeof MatrizesCurricularesRouteWithChildren
  TurmasRoute: typeof TurmasRouteWithChildren
  UnidadesRoute: typeof UnidadesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alunos': {
      id: '/alunos'
      path: '/alunos'
      fullPath: '/alunos'
      preLoaderRoute: typeof AlunosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matriculas': {
      id: '/matriculas'
      path: '/matriculas'
      fullPath: '/matriculas'
      preLoaderRoute: typeof MatriculasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matrizes-curriculares': {
      id: '/matrizes-curriculares'
      path: '/matrizes-curriculares'
      fullPath: '/matrizes-curriculares'
      preLoaderRoute: typeof MatrizesCurricularesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/turmas': {
      id: '/turmas'
      path: '/turmas'
      fullPath: '/turmas'
      preLoaderRoute: typeof TurmasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unidades': {
      id: '/unidades'
      path: '/unidades'
      fullPath: '/unidades'
      preLoaderRoute: typeof UnidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alunos/': {
      id: '/alunos/'
      path: '/'
      fullPath: '/alunos/'
      preLoaderRoute: typeof AlunosIndexRouteImport
      parentRoute: typeof AlunosRoute
    }
    '/alunos/$id': {
      id: '/alunos/$id'
      path: '/$id'
      fullPath: '/alunos/$id'
      preLoaderRoute: typeof AlunosIdRouteImport
      parentRoute: typeof AlunosRoute
    }
    '/alunos/novo': {
      id: '/alunos/novo'
      path: '/novo'
      fullPath: '/alunos/novo'
      preLoaderRoute: typeof AlunosNovoRouteImport
      parentRoute: typeof AlunosRoute
    }
    '/matrizes-curriculares/': {
      id: '/matrizes-curriculares/'
      path: '/'
      fullPath: '/matrizes-curriculares/'
      preLoaderRoute: typeof MatrizesCurricularesIndexRouteImport
      parentRoute: typeof MatrizesCurricularesRoute
    }
    '/matrizes-curriculares/$id': {
      id: '/matrizes-curriculares/$id'
      path: '/$id'
      fullPath: '/matrizes-curriculares/$id'
      preLoaderRoute: typeof MatrizesCurricularesIdRouteImport
      parentRoute: typeof MatrizesCurricularesRoute
    }
    '/matrizes-curriculares/nova': {
      id: '/matrizes-curriculares/nova'
      path: '/nova'
      fullPath: '/matrizes-curriculares/nova'
      preLoaderRoute: typeof MatrizesCurricularesNovaRouteImport
      parentRoute: typeof MatrizesCurricularesRoute
    }
    '/turmas/': {
      id: '/turmas/'
      path: '/'
      fullPath: '/turmas/'
      preLoaderRoute: typeof TurmasIndexRouteImport
      parentRoute: typeof TurmasRoute
    }
    '/turmas/$id': {
      id: '/turmas/$id'
      path: '/$id'
      fullPath: '/turmas/$id'
      preLoaderRoute: typeof TurmasIdRouteImport
      parentRoute: typeof TurmasRoute
    }
    '/turmas/nova': {
      id: '/turmas/nova'
      path: '/nova'
      fullPath: '/turmas/nova'
      preLoaderRoute: typeof TurmasNovaRouteImport
      parentRoute: typeof TurmasRoute
    }
    '/unidades/': {
      id: '/unidades/'
      path: '/'
      fullPath: '/unidades/'
      preLoaderRoute: typeof UnidadesIndexRouteImport
      parentRoute: typeof UnidadesRoute
    }
    '/unidades/$id': {
      id: '/unidades/$id'
      path: '/$id'
      fullPath: '/unidades/$id'
      preLoaderRoute: typeof UnidadesIdRouteImport
      parentRoute: typeof UnidadesRoute
    }
    '/alunos/editar/$id': {
      id: '/alunos/editar/$id'
      path: '/editar/$id'
      fullPath: '/alunos/editar/$id'
      preLoaderRoute: typeof AlunosEditarIdRouteImport
      parentRoute: typeof AlunosRoute
    }
    '/matrizes-curriculares/impressao/$id': {
      id: '/matrizes-curriculares/impressao/$id'
      path: '/impressao/$id'
      fullPath: '/matrizes-curriculares/impressao/$id'
      preLoaderRoute: typeof MatrizesCurricularesImpressaoIdRouteImport
      parentRoute: typeof MatrizesCurricularesRoute
    }
    '/matrizes-curriculares/nova-versao/$id': {
      id: '/matrizes-curriculares/nova-versao/$id'
      path: '/nova-versao/$id'
      fullPath: '/matrizes-curriculares/nova-versao/$id'
      preLoaderRoute: typeof MatrizesCurricularesNovaVersaoIdRouteImport
      parentRoute: typeof MatrizesCurricularesRoute
    }
    '/matrizes-curriculares/rascunho/$id': {
      id: '/matrizes-curriculares/rascunho/$id'
      path: '/rascunho/$id'
      fullPath: '/matrizes-curriculares/rascunho/$id'
      preLoaderRoute: typeof MatrizesCurricularesRascunhoIdRouteImport
      parentRoute: typeof MatrizesCurricularesRoute
    }
    '/turmas/editar/$id': {
      id: '/turmas/editar/$id'
      path: '/editar/$id'
      fullPath: '/turmas/editar/$id'
      preLoaderRoute: typeof TurmasEditarIdRouteImport
      parentRoute: typeof TurmasRoute
    }
  }
}

interface AlunosRouteChildren {
  AlunosIdRoute: typeof AlunosIdRoute
  AlunosNovoRoute: typeof AlunosNovoRoute
  AlunosIndexRoute: typeof AlunosIndexRoute
  AlunosEditarIdRoute: typeof AlunosEditarIdRoute
}

const AlunosRouteChildren: AlunosRouteChildren = {
  AlunosIdRoute: AlunosIdRoute,
  AlunosNovoRoute: AlunosNovoRoute,
  AlunosIndexRoute: AlunosIndexRoute,
  AlunosEditarIdRoute: AlunosEditarIdRoute,
}

const AlunosRouteWithChildren =
  AlunosRoute._addFileChildren(AlunosRouteChildren)

interface MatrizesCurricularesRouteChildren {
  MatrizesCurricularesIdRoute: typeof MatrizesCurricularesIdRoute
  MatrizesCurricularesNovaRoute: typeof MatrizesCurricularesNovaRoute
  MatrizesCurricularesIndexRoute: typeof MatrizesCurricularesIndexRoute
  MatrizesCurricularesImpressaoIdRoute: typeof MatrizesCurricularesImpressaoIdRoute
  MatrizesCurricularesNovaVersaoIdRoute: typeof MatrizesCurricularesNovaVersaoIdRoute
  MatrizesCurricularesRascunhoIdRoute: typeof MatrizesCurricularesRascunhoIdRoute
}

const MatrizesCurricularesRouteChildren: MatrizesCurricularesRouteChildren = {
  MatrizesCurricularesIdRoute: MatrizesCurricularesIdRoute,
  MatrizesCurricularesNovaRoute: MatrizesCurricularesNovaRoute,
  MatrizesCurricularesIndexRoute: MatrizesCurricularesIndexRoute,
  MatrizesCurricularesImpressaoIdRoute: MatrizesCurricularesImpressaoIdRoute,
  MatrizesCurricularesNovaVersaoIdRoute: MatrizesCurricularesNovaVersaoIdRoute,
  MatrizesCurricularesRascunhoIdRoute: MatrizesCurricularesRascunhoIdRoute,
}

const MatrizesCurricularesRouteWithChildren =
  MatrizesCurricularesRoute._addFileChildren(MatrizesCurricularesRouteChildren)

interface TurmasRouteChildren {
  TurmasIdRoute: typeof TurmasIdRoute
  TurmasNovaRoute: typeof TurmasNovaRoute
  TurmasIndexRoute: typeof TurmasIndexRoute
  TurmasEditarIdRoute: typeof TurmasEditarIdRoute
}

const TurmasRouteChildren: TurmasRouteChildren = {
  TurmasIdRoute: TurmasIdRoute,
  TurmasNovaRoute: TurmasNovaRoute,
  TurmasIndexRoute: TurmasIndexRoute,
  TurmasEditarIdRoute: TurmasEditarIdRoute,
}

const TurmasRouteWithChildren =
  TurmasRoute._addFileChildren(TurmasRouteChildren)

interface UnidadesRouteChildren {
  UnidadesIdRoute: typeof UnidadesIdRoute
  UnidadesIndexRoute: typeof UnidadesIndexRoute
}

const UnidadesRouteChildren: UnidadesRouteChildren = {
  UnidadesIdRoute: UnidadesIdRoute,
  UnidadesIndexRoute: UnidadesIndexRoute,
}

const UnidadesRouteWithChildren = UnidadesRoute._addFileChildren(
  UnidadesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlunosRoute: AlunosRouteWithChildren,
  DesignSystemRoute: DesignSystemRoute,
  LoginRoute: LoginRoute,
  MatriculasRoute: MatriculasRoute,
  MatrizesCurricularesRoute: MatrizesCurricularesRouteWithChildren,
  TurmasRoute: TurmasRouteWithChildren,
  UnidadesRoute: UnidadesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
