/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MatrizesCurricularesRouteImport } from './routes/matrizes-curriculares'
import { Route as UnidadesRouteImport } from './routes/unidades'
import { Route as MatrizesCurricularesIndexRouteImport } from './routes/matrizes-curriculares.index'
import { Route as MatrizesCurricularesIdRouteImport } from './routes/matrizes-curriculares.$id'
import { Route as MatrizesCurricularesNovaRouteImport } from './routes/matrizes-curriculares.nova'
import { Route as UnidadesIndexRouteImport } from './routes/unidades.index'
import { Route as UnidadesIdRouteImport } from './routes/unidades.$id'
import { Route as MatrizesCurricularesImpressaoIdRouteImport } from './routes/matrizes-curriculares.impressao.$id'
import { Route as MatrizesCurricularesNovaVersaoIdRouteImport } from './routes/matrizes-curriculares.nova-versao.$id'
import { Route as MatrizesCurricularesRascunhoIdRouteImport } from './routes/matrizes-curriculares.rascunho.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MatrizesCurricularesRoute = MatrizesCurricularesRouteImport.update({
  id: '/matrizes-curriculares',
  path: '/matrizes-curriculares',
  getParentRoute: () => rootRouteImport,
} as any)
const UnidadesRoute = UnidadesRouteImport.update({
  id: '/unidades',
  path: '/unidades',
  getParentRoute: () => rootRouteImport,
} as any)
const MatrizesCurricularesIndexRoute =
  MatrizesCurricularesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => MatrizesCurricularesRoute,
  } as any)
const MatrizesCurricularesIdRoute = MatrizesCurricularesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MatrizesCurricularesRoute,
} as any)
const MatrizesCurricularesNovaRoute =
  MatrizesCurricularesNovaRouteImport.update({
    id: '/nova',
    path: '/nova',
    getParentRoute: () => MatrizesCurricularesRoute,
  } as any)
const UnidadesIndexRoute = UnidadesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UnidadesRoute,
} as any)
const UnidadesIdRoute = UnidadesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => UnidadesRoute,
} as any)
const MatrizesCurricularesImpressaoIdRoute =
  MatrizesCurricularesImpressaoIdRouteImport.update({
    id: '/impressao/$id',
    path: '/impressao/$id',
    getParentRoute: () => MatrizesCurricularesRoute,
  } as any)
const MatrizesCurricularesNovaVersaoIdRoute =
  MatrizesCurricularesNovaVersaoIdRouteImport.update({
    id: '/nova-versao/$id',
    path: '/nova-versao/$id',
    getParentRoute: () => MatrizesCurricularesRoute,
  } as any)
const MatrizesCurricularesRascunhoIdRoute =
  MatrizesCurricularesRascunhoIdRouteImport.update({
    id: '/rascunho/$id',
    path: '/rascunho/$id',
    getParentRoute: () => MatrizesCurricularesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/design-system': typeof DesignSystemRoute
  '/login': typeof LoginRoute
  '/matrizes-curriculares': typeof MatrizesCurricularesRouteWithChildren
  '/unidades': typeof UnidadesRouteWithChildren
  '/matrizes-curriculares/$id': typeof MatrizesCurricularesIdRoute
  '/matrizes-curriculares/nova': typeof MatrizesCurricularesNovaRoute
  '/unidades/$id': typeof UnidadesIdRoute
  '/matrizes-curriculares/': typeof MatrizesCurricularesIndexRoute
  '/unidades/': typeof UnidadesIndexRoute
  '/matrizes-curriculares/impressao/$id': typeof MatrizesCurricularesImpressaoIdRoute
  '/matrizes-curriculares/nova-versao/$id': typeof MatrizesCurricularesNovaVersaoIdRoute
  '/matrizes-curriculares/rascunho/$id': typeof MatrizesCurricularesRascunhoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design-system': typeof DesignSystemRoute
  '/login': typeof LoginRoute
  '/matrizes-curriculares/$id': typeof MatrizesCurricularesIdRoute
  '/matrizes-curriculares/nova': typeof MatrizesCurricularesNovaRoute
  '/unidades/$id': typeof UnidadesIdRoute
  '/matrizes-curriculares': typeof MatrizesCurricularesIndexRoute
  '/unidades': typeof UnidadesIndexRoute
  '/matrizes-curriculares/impressao/$id': typeof MatrizesCurricularesImpressaoIdRoute
  '/matrizes-curriculares/nova-versao/$id': typeof MatrizesCurricularesNovaVersaoIdRoute
  '/matrizes-curriculares/rascunho/$id': typeof MatrizesCurricularesRascunhoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/design-system': typeof DesignSystemRoute
  '/login': typeof LoginRoute
  '/matrizes-curriculares': typeof MatrizesCurricularesRouteWithChildren
  '/unidades': typeof UnidadesRouteWithChildren
  '/matrizes-curriculares/$id': typeof MatrizesCurricularesIdRoute
  '/matrizes-curriculares/nova': typeof MatrizesCurricularesNovaRoute
  '/unidades/$id': typeof UnidadesIdRoute
  '/matrizes-curriculares/': typeof MatrizesCurricularesIndexRoute
  '/unidades/': typeof UnidadesIndexRoute
  '/matrizes-curriculares/impressao/$id': typeof MatrizesCurricularesImpressaoIdRoute
  '/matrizes-curriculares/nova-versao/$id': typeof MatrizesCurricularesNovaVersaoIdRoute
  '/matrizes-curriculares/rascunho/$id': typeof MatrizesCurricularesRascunhoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/design-system'
    | '/login'
    | '/matrizes-curriculares'
    | '/unidades'
    | '/matrizes-curriculares/$id'
    | '/matrizes-curriculares/nova'
    | '/unidades/$id'
    | '/matrizes-curriculares/'
    | '/unidades/'
    | '/matrizes-curriculares/impressao/$id'
    | '/matrizes-curriculares/nova-versao/$id'
    | '/matrizes-curriculares/rascunho/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/design-system'
    | '/login'
    | '/matrizes-curriculares/$id'
    | '/matrizes-curriculares/nova'
    | '/unidades/$id'
    | '/matrizes-curriculares'
    | '/unidades'
    | '/matrizes-curriculares/impressao/$id'
    | '/matrizes-curriculares/nova-versao/$id'
    | '/matrizes-curriculares/rascunho/$id'
  id:
    | '__root__'
    | '/'
    | '/design-system'
    | '/login'
    | '/matrizes-curriculares'
    | '/unidades'
    | '/matrizes-curriculares/$id'
    | '/matrizes-curriculares/nova'
    | '/unidades/$id'
    | '/matrizes-curriculares/'
    | '/unidades/'
    | '/matrizes-curriculares/impressao/$id'
    | '/matrizes-curriculares/nova-versao/$id'
    | '/matrizes-curriculares/rascunho/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DesignSystemRoute: typeof DesignSystemRoute
  LoginRoute: typeof LoginRoute
  MatrizesCurricularesRoute: typeof MatrizesCurricularesRouteWithChildren
  UnidadesRoute: typeof UnidadesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matrizes-curriculares': {
      id: '/matrizes-curriculares'
      path: '/matrizes-curriculares'
      fullPath: '/matrizes-curriculares'
      preLoaderRoute: typeof MatrizesCurricularesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unidades': {
      id: '/unidades'
      path: '/unidades'
      fullPath: '/unidades'
      preLoaderRoute: typeof UnidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matrizes-curriculares/': {
      id: '/matrizes-curriculares/'
      path: '/'
      fullPath: '/matrizes-curriculares/'
      preLoaderRoute: typeof MatrizesCurricularesIndexRouteImport
      parentRoute: typeof MatrizesCurricularesRoute
    }
    '/matrizes-curriculares/$id': {
      id: '/matrizes-curriculares/$id'
      path: '/$id'
      fullPath: '/matrizes-curriculares/$id'
      preLoaderRoute: typeof MatrizesCurricularesIdRouteImport
      parentRoute: typeof MatrizesCurricularesRoute
    }
    '/matrizes-curriculares/nova': {
      id: '/matrizes-curriculares/nova'
      path: '/nova'
      fullPath: '/matrizes-curriculares/nova'
      preLoaderRoute: typeof MatrizesCurricularesNovaRouteImport
      parentRoute: typeof MatrizesCurricularesRoute
    }
    '/unidades/': {
      id: '/unidades/'
      path: '/'
      fullPath: '/unidades/'
      preLoaderRoute: typeof UnidadesIndexRouteImport
      parentRoute: typeof UnidadesRoute
    }
    '/unidades/$id': {
      id: '/unidades/$id'
      path: '/$id'
      fullPath: '/unidades/$id'
      preLoaderRoute: typeof UnidadesIdRouteImport
      parentRoute: typeof UnidadesRoute
    }
    '/matrizes-curriculares/impressao/$id': {
      id: '/matrizes-curriculares/impressao/$id'
      path: '/impressao/$id'
      fullPath: '/matrizes-curriculares/impressao/$id'
      preLoaderRoute: typeof MatrizesCurricularesImpressaoIdRouteImport
      parentRoute: typeof MatrizesCurricularesRoute
    }
    '/matrizes-curriculares/nova-versao/$id': {
      id: '/matrizes-curriculares/nova-versao/$id'
      path: '/nova-versao/$id'
      fullPath: '/matrizes-curriculares/nova-versao/$id'
      preLoaderRoute: typeof MatrizesCurricularesNovaVersaoIdRouteImport
      parentRoute: typeof MatrizesCurricularesRoute
    }
    '/matrizes-curriculares/rascunho/$id': {
      id: '/matrizes-curriculares/rascunho/$id'
      path: '/rascunho/$id'
      fullPath: '/matrizes-curriculares/rascunho/$id'
      preLoaderRoute: typeof MatrizesCurricularesRascunhoIdRouteImport
      parentRoute: typeof MatrizesCurricularesRoute
    }
  }
}

interface MatrizesCurricularesRouteChildren {
  MatrizesCurricularesIdRoute: typeof MatrizesCurricularesIdRoute
  MatrizesCurricularesNovaRoute: typeof MatrizesCurricularesNovaRoute
  MatrizesCurricularesIndexRoute: typeof MatrizesCurricularesIndexRoute
  MatrizesCurricularesImpressaoIdRoute: typeof MatrizesCurricularesImpressaoIdRoute
  MatrizesCurricularesNovaVersaoIdRoute: typeof MatrizesCurricularesNovaVersaoIdRoute
  MatrizesCurricularesRascunhoIdRoute: typeof MatrizesCurricularesRascunhoIdRoute
}

const MatrizesCurricularesRouteChildren: MatrizesCurricularesRouteChildren = {
  MatrizesCurricularesIdRoute: MatrizesCurricularesIdRoute,
  MatrizesCurricularesNovaRoute: MatrizesCurricularesNovaRoute,
  MatrizesCurricularesIndexRoute: MatrizesCurricularesIndexRoute,
  MatrizesCurricularesImpressaoIdRoute: MatrizesCurricularesImpressaoIdRoute,
  MatrizesCurricularesNovaVersaoIdRoute: MatrizesCurricularesNovaVersaoIdRoute,
  MatrizesCurricularesRascunhoIdRoute: MatrizesCurricularesRascunhoIdRoute,
}

const MatrizesCurricularesRouteWithChildren =
  MatrizesCurricularesRoute._addFileChildren(MatrizesCurricularesRouteChildren)

interface UnidadesRouteChildren {
  UnidadesIdRoute: typeof UnidadesIdRoute
  UnidadesIndexRoute: typeof UnidadesIndexRoute
}

const UnidadesRouteChildren: UnidadesRouteChildren = {
  UnidadesIdRoute: UnidadesIdRoute,
  UnidadesIndexRoute: UnidadesIndexRoute,
}

const UnidadesRouteWithChildren = UnidadesRoute._addFileChildren(
  UnidadesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DesignSystemRoute: DesignSystemRoute,
  LoginRoute: LoginRoute,
  MatrizesCurricularesRoute: MatrizesCurricularesRouteWithChildren,
  UnidadesRoute: UnidadesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
