REVOKE EXECUTE ON FUNCTION public.can_read_collegial(text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.collegial_conduct_authority(text, integer, text) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.record_collegial_session_event(text, text, uuid, jsonb, text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.record_collegial_deliberation(text, uuid, jsonb, text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.close_collegial_minute(text, uuid, text, jsonb, text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.register_academic_standings(text, text, text, jsonb) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.apply_assessment_instrument(text, uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.can_read_collegial(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.record_collegial_session_event(text, text, uuid, jsonb, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.record_collegial_deliberation(text, uuid, jsonb, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.close_collegial_minute(text, uuid, text, jsonb, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.register_academic_standings(text, text, text, jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.apply_assessment_instrument(text, uuid) TO authenticated;